CREATE TABLE `users` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL
);

CREATE TABLE `board` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user_id` BIGINT NOT NULL,
  CONSTRAINT `fk_board_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `todo` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `board_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `is_completed` BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT `fk_todo_board` FOREIGN KEY (`board_id`) REFERENCES `board` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_todo_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

